---
- name: Install Python Packages
  become: yes
  pip:
      name: "{{item}}"
      state: latest
  with_items:
  - "localstack"

- name: Install Kubernetes' kubectl
  become: yes
  get_url:
      url: "https://storage.googleapis.com/kubernetes-release/release/{{ kubernetetes_release }}/bin/linux/amd64/kubectl"
      dest: "/usr/local/bin/kubectl"
      mode: 0555

- name: Grab Helm Tarball
  become: no
  unarchive:
      src: "https://storage.googleapis.com/kubernetes-helm/helm-{{ helm_release }}-linux-amd64.tar.gz"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}"
      copy: no
      mode: 0555
      creates: "{{ansible_user_dir}}/{{base_download_directory}}/linux-amd64/LICENSE"

- name: Copy Helm Binary
  become: yes
  copy:
      src: "{{ansible_user_dir}}/{{base_download_directory}}/linux-amd64/helm"
      dest: "/usr/local/bin/helm"
      remote_src: yes
      mode: 0555
      backup: no

- name: Install Kubernetes' kops
  become: yes
  get_url:
      url: "https://github.com/kubernetes/kops/releases/download/{{ kops_release }}/kops-linux-amd64"
      dest: "/usr/local/bin/kops"
      mode: 0555

- name: Install jq
  become: yes
  get_url:
      url: "https://github.com/stedolan/jq/releases/download/{{ jq_release }}/jq-linux64"
      dest: "/usr/local/bin/jq"
      mode: 0555

- name: Download Sysdig Installation Script
  become: no
  get_url:
      url: "https://s3.amazonaws.com/download.draios.com/stable/install-sysdig"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/install-sysdig"
      mode: 0555
  when: operations_sysdig_install

- name: Run Sysdig Installation Script
  become: yes
  shell: "{{ansible_user_dir}}/{{base_download_directory}}/install-sysdig"
  args:
      creates: "/usr/bin/csysdig"
  when: operations_sysdig_install

- name: Test Sysdig
  become: no
  command: /usr/bin/csysdig --version
  when: operations_sysdig_install

- name: Place Loggly Configuration File
  become: yes
  template:
      src: templates/22-loggly.conf.j2
      dest: /etc/rsyslog.d/22-loggly.conf
      owner: root
      group: root
      mode: 444
      backup: no
  when: operations_loggly_install

- name: Restart Syslog
  become: yes
  service:
      name: rsyslog
      state: restarted
  when: operations_loggly_install

- name: Test Loggly
  become: no
  command: "/usr/bin/logger 'Hello World!'"
  when: operations_loggly_install

- name: Add Datadog Repository Key
  become: yes
  apt_key:
      keyserver: keyserver.ubuntu.com
      id: 382E94DE
      state: present
  when: operations_datadog_install and (ansible_distribution == "Ubuntu")

- name: Add Datadog Repository
  become: yes
  apt_repository:
      repo: 'deb https://apt.datadoghq.com/ stable main'
      update_cache: yes
      state: present
  when: operations_datadog_install and (ansible_distribution == "Ubuntu")

- name: Add Datadog Repository
  become: yes
  yum_repository:
      name: datadog
      description: "Datadog monitoring agent"
      baseurl: "https://yum.datadoghq.com/rpm/x86_64/"
      gpgkey: "https://yum.datadoghq.com/DATADOG_RPM_KEY.public"
      gpgcheck: yes
      state: present
  when: operations_datadog_install and (ansible_distribution == "Fedora")

- name: Install Datadog Package
  become: yes
  package:
      name: "{{item}}"
      state: present
      allow_unauthenticated: yes
  with_items:
  - "datadog-agent"
  when: operations_datadog_install and (ansible_distribution == "Ubuntu")

- name: Install Datadog Package
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "datadog-agent"
  when: operations_datadog_install and (ansible_distribution == "Fedora")

- name: Place Datadog Configuration File
  become: yes
  template:
      src: templates/datadog.conf.j2
      dest: /etc/dd-agent/datadog.conf
      owner: root
      group: root
      mode: 444
      backup: no
  when: operations_datadog_install and (ansible_distribution != "CentOS")

- name: Restart Datadog
  become: yes
  service:
      name: datadog-agent
      state: restarted
  when: operations_datadog_install and (ansible_distribution != "CentOS")

- name: Download Falco Installation Script
  become: no
  get_url:
      url: "https://s3.amazonaws.com/download.draios.com/stable/install-falco"
      dest: "{{ansible_user_dir}}/{{base_download_directory}}/install-falco"
      mode: 0555
  when: operations_falco_install

- name: Run Falco Installation Script
  become: yes
  shell: "{{ansible_user_dir}}/{{base_download_directory}}/install-falco"
  args:
      creates: "/usr/bin/falco"
  when: operations_falco_install

- name: Test Falco
  become: no
  command: /usr/bin/falco --version
  when: operations_falco_install

