---
- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "curl"
  - "python-pip"

- name: Install AWS CLI
  become: yes
  pip:
      name: "{{item}}"
      state: latest
  with_items:
  - "pip"
  - "awscli"
  when: aws_cli_install

- name: Test AWS CLI
  become: no
  command: /usr/local/bin/aws --version
  when: aws_cli_install

- name: Download AWS ECS CLI
  become: yes
  get_url:
      url: "https://s3.amazonaws.com/amazon-ecs-cli/ecs-cli-linux-amd64-latest"
      dest: "/usr/local/bin/ecs-cli"
      mode: 0555
  when: aws_ecs_cli_install

- name: Test AWS ECS CLI
  become: no
  command: /usr/local/bin/ecs-cli --version
  when: aws_ecs_cli_install



