---
- name: Create privledged folders
  become: yes
  file:
      path: "{{item}}"
      state: directory
      mode: 0755
      recurse: yes
  with_items:
  - "{{ansible_user_dir}}/{{operations_download_directory}}"

- name: Install Required Packages
  become: yes
  package:
      name: "{{item}}"
      state: present
  with_items:
  - "curl"
  - "ca-certificates"

- name: Download Sysdig
  become: yes
  get_url:
      url: "https://s3.amazonaws.com/download.draios.com/stable/install-sysdig"
      dest: "{{ansible_user_dir}}/{{operations_download_directory}}/install-sysdig"
      mode: 0555
  when: operations_sysdig_install

- name: Install Sysdig
  become: yes
  shell: "{{ansible_user_dir}}/{{operations_download_directory}}/install-sysdig"
  args:
      creates: "/usr/bin/csysdig"
  when: operations_sysdig_install

- name: Test Sysdig
  become: no
  command: /usr/bin/csysdig --version
  when: operations_sysdig_install



